/*
 * Copyright (c) 2016 Jonathan Glines
 * Jonathan Glines <jonathan@glines.net>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#include <assert.h>

#include "transvoxel_canonical_cell_tables.c"
#include "transvoxel_canonical_cells.h"

#include <mc/algorithms/transvoxel/canonical.h>

/* NOTE: This is a little bit awkward, but it is difficult to export the
 * generated list of canonical cells as an enum type. */
const int mcTransvoxel_canonicalTransitionCells[] = {
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_0,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_1,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_2,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_3,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_4,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_5,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_6,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_7,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_8,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_9,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_10,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_11,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_12,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_13,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_14,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_15,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_16,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_17,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_18,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_19,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_20,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_21,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_22,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_23,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_24,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_25,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_26,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_27,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_28,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_29,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_30,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_31,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_32,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_33,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_34,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_35,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_36,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_37,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_38,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_39,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_40,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_41,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_42,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_43,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_44,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_45,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_46,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_47,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_48,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_49,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_50,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_51,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_52,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_53,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_54,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_55,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_56,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_57,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_58,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_59,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_60,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_61,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_62,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_63,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_64,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_65,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_66,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_67,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_68,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_69,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_70,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_71,
  MC_TRANSVOXEL_CANONICAL_TRANSITION_CELL_72,
};

int mcTransvoxel_canonicalTransitionCell(int cell) {
  assert((cell & ~(0x1ff)) == 0);
  return mcTransvoxel_canonicalTransitionCellTable[cell];
}

int mcTransvoxel_canonicalTransitionCellSequence(int cell) {
  assert((cell & ~(0x1ff)) == 0);
  return mcTransvoxel_canonicalTransitionCellSequenceTable[cell];
}
